sass:
  load_paths:
    - _sass
    - node_modules

destination: ./docs

baseurl: /project_page_site

exclude:
  - node_modules
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock

include:
  - .nojekyll

plugins:
  - octopress-autoprefixer
